### ISSUE TITLE
Incorrect parsing of string literals containing digits

### ISSUE THREAD

**Issue by remuladgryta** [blinry/legit#2]
Steps to reproduce:
`git commit -m "\"3\" put"`
expected output:
`3 (0x33)`
or possibly if one wants to interpret the language specification in a particularly obtuse manner:
`ETX (0x03)`
actual output:
`NUL (0x00)`

I'm not experienced with Ruby but it looks to me like the issue arises when matching `command`. `/\d+/` matches any sequence of characters containing digits before `/^".*"$/` gets a chance to match string literals. Changing the regex to `/^\d+$/` would solve this. From what I can tell, Ruby's `String#to_i` does not parse alternative integer literal forms like `0x00` or `\000` so this should not be a regression.

**Comment by blinry** [comment]
Thanks for fixing this, I absolutely agree! Thanks for writing such a thoughtful reasoning!
